#: import CardTransition kivy.uix.screenmanager.CardTransition

<InitialScreen>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 100
        spacing: 50
        Image:
            source: "assets/logo-solvimm.png"
            allow_stretch: True
        Spinner:
            id: spinner_id
            text: "Profile"
            values: []
            on_text: root.spinner_clicked(spinner_id.text)
        Label:
            text: ""